param([string]$Root = (Split-Path -Parent $PSScriptRoot), [string]$QuestionFile, [switch]$NoExit)
$ErrorCount=0; $WarningCount=0
function Add-Result($Level,$Message) { if($Level -eq 'ERROR'){$script:ErrorCount++}elseif($Level -eq 'WARNING'){$script:WarningCount++}; Write-Host "$Level`: $Message" }
function Read-Json($Path) { try { Get-Content -LiteralPath $Path -Raw -Encoding utf8 -ErrorAction Stop | ConvertFrom-Json -ErrorAction Stop } catch { Add-Result 'ERROR' "Invalid JSON: $Path ($($_.Exception.Message))"; $null } }
function Test-Question($Q,$ExpectedGrade,$Seen,$Origin,$Scenes,$Audio) {
  $id=[string]$Q.id; if(!$id){Add-Result 'ERROR' "${Origin}: missing question id";return}; if($Seen.ContainsKey($id)){Add-Result 'ERROR' "${Origin}: duplicate ID $id"}else{$Seen[$id]=$true}
  if($id -notmatch '^(G5|G4|G3|GP2|GP2PLUS|G2|GP1|G1|P2|P2P|P1)-(R|L|W|S|V)-(P[0-9]+|LEGACY)-[0-9]{4}$'){Add-Result 'ERROR' "${Origin}: invalid ID format $id"}
  if(!$Q.grade){Add-Result 'ERROR' "${Origin}: $id has no grade"}elseif($ExpectedGrade -and $Q.grade -ne $ExpectedGrade){Add-Result 'ERROR' "${Origin}: $id grade does not match $ExpectedGrade"}; if(!$Q.skill){Add-Result 'ERROR' "${Origin}: $id has no skill"}; if(!$Q.part){Add-Result 'ERROR' "${Origin}: $id has no part"}; if(!$Q.sourceType){Add-Result 'ERROR' "${Origin}: $id has no sourceType"}; if(-not $Q.PSObject.Properties.Name.Contains('reviewStatus')){Add-Result 'WARNING' "${Origin}: $id has no reviewStatus (legacy-compatible warning)"}
  if($Q.choices){$choiceIds=@{};foreach($choice in $Q.choices){if(!$choice.id){Add-Result 'ERROR' "${Origin}: $id has a choice without ID"}elseif($choiceIds.ContainsKey($choice.id)){Add-Result 'ERROR' "${Origin}: $id has duplicate choice ID $($choice.id)"}else{$choiceIds[$choice.id]=$true}};if(!$Q.correctChoiceId){Add-Result 'ERROR' "${Origin}: $id has choices but no correctChoiceId"}elseif(-not $choiceIds.ContainsKey($Q.correctChoiceId)){Add-Result 'ERROR' "${Origin}: $id correctChoiceId does not exist"}}
  if($Q.media){$ir=[string]$Q.media.imageRef;$ar=[string]$Q.media.audioRef;if($ir -and -not $Scenes.ContainsKey($ir) -and -not(Test-Path (Join-Path $Root $ir))){Add-Result 'ERROR' "${Origin}: $id imageRef does not exist: $ir"};if($ar -and -not $Audio.ContainsKey($ar) -and -not(Test-Path (Join-Path $Root $ar))){Add-Result 'ERROR' "${Origin}: $id audioRef does not exist: $ar"}}
}
$sceneIds=@{};$audioIds=@{};$sceneCatalog=Join-Path $Root 'data/assets/scenes.json';if(Test-Path $sceneCatalog){$s=Read-Json $sceneCatalog;if($s){foreach($item in @($s.scenes)){$sceneIds[$item.sceneId]=$true}}};$audioCatalog=Join-Path $Root 'data/assets/audio.json';if(Test-Path $audioCatalog){$a=Read-Json $audioCatalog;if($a){foreach($item in @($a.audio)){$audioIds[$item.audioId]=$true}}};$seen=@{}
if($QuestionFile){$data=Read-Json $QuestionFile;if($data){foreach($q in @($data.questions)){Test-Question $q '' $seen $QuestionFile $sceneIds $audioIds}}}else{$catalog=Read-Json (Join-Path $Root 'data/catalog.json');if($catalog){foreach($grade in @($catalog.grades)){if(!$grade.manifest){continue};$manifestPath=Join-Path $Root $grade.manifest;if(-not(Test-Path $manifestPath)){Add-Result 'ERROR' "Manifest does not exist: $($grade.manifest)";continue};$manifest=Read-Json $manifestPath;if(!$manifest){continue};$dir=Split-Path -Parent $manifestPath;$files=@();if($manifest.dataFiles){$files=@($manifest.dataFiles|ForEach-Object{Join-Path $Root $_})}else{Add-Result 'WARNING' "$($grade.id): manifest has no dataFiles; using legacy reading.json discovery";$files=@(Get-ChildItem -LiteralPath $dir -Filter 'reading.json' -File -ErrorAction SilentlyContinue|Select-Object -ExpandProperty FullName)};foreach($file in $files){if(-not(Test-Path $file)){Add-Result 'ERROR' "Question data file does not exist: $file";continue};$data=Read-Json $file;if($data){foreach($q in @($data.questions)){Test-Question $q $grade.id $seen $file $sceneIds $audioIds}}}}}}
if(-not $QuestionFile -and $catalog){foreach($grade in @($catalog.grades)){if(!$grade.manifest){continue};$manifest=Read-Json (Join-Path $Root $grade.manifest);if($manifest -and $manifest.contentRoutes){foreach($route in @($manifest.contentRoutes)){$routePath=Join-Path $Root $route.file;if(-not(Test-Path $routePath)){Add-Result 'ERROR' "$($grade.id): route file does not exist: $($route.file)";continue};$routeData=Read-Json $routePath;if(!$routeData){continue};$matches=@($routeData.questions|Where-Object{$_.grade -eq $grade.id -and $_.skill -eq $route.skill -and $_.part -eq $route.part});if($matches.Count -ne [int]$route.expectedQuestionCount){Add-Result 'ERROR' "$($grade.id): $($route.skill) $($route.part) expected $($route.expectedQuestionCount) but found $($matches.Count)"};foreach($question in $matches){if($question.id -notmatch "^$([regex]::Escape($grade.idPrefix))-[RLSWV]-$($route.part)-"){Add-Result 'ERROR' "$($grade.id): route question ID does not match $($route.part): $($question.id)"};if($question.choices -and -not(@($question.choices.id) -contains $question.correctChoiceId)){Add-Result 'ERROR' "$($grade.id): route question has invalid correctChoiceId: $($question.id)"}}}}}}
Write-Output "SUMMARY: errors=$ErrorCount warnings=$WarningCount";if(-not $NoExit -and $ErrorCount -gt 0){exit 1}
